version: "3.8"

volumes:
  php-fpm-socket:
  db-store:

services:
  # php
  app:
    container_name: php
    build: ./infra/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  # nginx
  web:
    container_name: nginx
    build: ./infra/docker/nginx
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  # MySQL
  db:
    container_name: db-host
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
